services:
#  app:
#    container_name: back
#    build:
#      context: .
#      dockerfile: Dockerfile
#    #    command: ["tail", "-f", "/dev/null"]
#    command: [ "zero2hero", "-c", "/etc/zero2hero/docker-config.yaml" ]
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - db
#    networks:
#      - applet
  db:
    container_name: db
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: applet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - applet

volumes:
  db_data:

networks:
  applet: