application_port: 8080
database:
  # Switch to "db" when running in Docker mode
#  host: "db"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "applet"
  require_ssl: false